services:
  - type: web
    name: hng-stage0-api
    runtime: docker
    branch: main
    healthCheckPath: /api/health
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
