services:
  - type: web
    name: hng-stage0-api
    runtime: docker
    plan: free
    healthCheckPath: /api/info
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
